# Generated by Django 5.2.6 on 2025-09-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('set_type', models.CharField(choices=[('compare', 'Compare Set'), ('portfolio', 'Portfolio'), ('watchlist', 'Watchlist')], max_length=20, verbose_name='Set Type')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved Set',
                'verbose_name_plural': 'Saved Sets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'set_type'], name='activity_sa_user_id_5fa1d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('view_type', models.CharField(choices=[('info', 'Info'), ('compare', 'Compare'), ('portfolio', 'Portfolio')], default='info', max_length=20, verbose_name='View Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'View Event',
                'verbose_name_plural': 'View Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activity_vi_user_id_8b6742_idx'), models.Index(fields=['symbol', '-timestamp'], name='activity_vi_symbol_33812c_idx')],
            },
        ),
    ]
