# Generated by Django 5.2.6 on 2025-09-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('exchange', models.CharField(blank=True, max_length=50, verbose_name='Exchange')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Fundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Period')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='P/E Ratio')),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='P/B Ratio')),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Debt to Equity')),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ROE')),
                ('roa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='ROA')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Current Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='data.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Fundamentals',
                'verbose_name_plural': 'Fundamentals',
                'ordering': ['-period'],
                'unique_together': {('instrument', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CachedWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('prices', 'Prices'), ('fundamentals', 'Fundamentals')], max_length=20, verbose_name='Window Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_windows', to='data.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Cached Window',
                'verbose_name_plural': 'Cached Windows',
                'unique_together': {('instrument', 'window_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='PriceOHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Open Price')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='High Price')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Low Price')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Close Price')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Adjusted Close')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='data.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Price OHLC',
                'verbose_name_plural': 'Price OHLC',
                'ordering': ['-date'],
                'unique_together': {('instrument', 'date')},
            },
        ),
    ]
