# Generated by Django 5.2.7 on 2025-10-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(choices=[('precious_metals', 'Precious Metals'), ('energy', 'Energy'), ('agriculture', 'Agriculture'), ('industrial', 'Industrial'), ('livestock', 'Livestock'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('exchange', models.CharField(blank=True, max_length=50, verbose_name='Exchange')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CommoditiesQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Price')),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Change')),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Change Percentage')),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Day Low')),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Day High')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='data.commodity', verbose_name='Commodity')),
            ],
            options={
                'verbose_name': 'Commodity Quote',
                'verbose_name_plural': 'Commodity Quotes',
                'ordering': ['-timestamp'],
                'unique_together': {('commodity', 'timestamp')},
            },
        ),
    ]
