# Generated by Django 5.2.7 on 2025-10-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_commodity_commoditiesquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('circulating_supply', models.BigIntegerField(blank=True, null=True, verbose_name='Circulating Supply')),
                ('total_supply', models.BigIntegerField(blank=True, null=True, verbose_name='Total Supply')),
                ('max_supply', models.BigIntegerField(blank=True, null=True, verbose_name='Max Supply')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CryptocurrencyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Open Price')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='High Price')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Low Price')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Close Price')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='data.cryptocurrency', verbose_name='Cryptocurrency')),
            ],
            options={
                'verbose_name': 'Cryptocurrency Quote',
                'verbose_name_plural': 'Cryptocurrency Quotes',
                'ordering': ['-timestamp'],
                'unique_together': {('cryptocurrency', 'timestamp')},
            },
        ),
    ]
