# Generated by Django 5.2.7 on 2025-10-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_cryptocurrency_cryptocurrencyquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('base_currency', models.CharField(max_length=3, verbose_name='Base Currency')),
                ('quote_currency', models.CharField(max_length=3, verbose_name='Quote Currency')),
                ('exchange', models.CharField(blank=True, max_length=50, verbose_name='Exchange')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Forex',
                'verbose_name_plural': 'Forex',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ForexQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Open Price')),
                ('high_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='High Price')),
                ('low_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Low Price')),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Close Price')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('forex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='data.forex', verbose_name='Forex')),
            ],
            options={
                'verbose_name': 'Forex Quote',
                'verbose_name_plural': 'Forex Quotes',
                'ordering': ['-timestamp'],
                'unique_together': {('forex', 'timestamp')},
            },
        ),
    ]
