# Generated by Django 5.2.7 on 2025-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_forex_forexquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Exchange Code')),
                ('name', models.CharField(max_length=200, verbose_name='Exchange Name')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Country Name')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Country Code')),
                ('symbol_suffix', models.CharField(blank=True, max_length=10, verbose_name='Symbol Suffix')),
                ('delay', models.CharField(blank=True, max_length=20, verbose_name='Data Delay')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'ordering': ['name'],
            },
        ),
    ]
