# Generated by Django 5.2.7 on 2025-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='trade_month',
            field=models.CharField(blank=True, max_length=10, verbose_name='Trade Month'),
        ),
    ]
