# Generated by Django 5.2.7 on 2025-10-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_commodity_trade_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Exchange'),
        ),
    ]
