# Generated by Django 5.2.7 on 2025-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_commodity_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='from_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='From Currency'),
        ),
        migrations.AddField(
            model_name='forex',
            name='from_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='From Currency Name'),
        ),
        migrations.AddField(
            model_name='forex',
            name='to_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='To Currency'),
        ),
        migrations.AddField(
            model_name='forex',
            name='to_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='To Currency Name'),
        ),
    ]
