# Generated by Django 5.2.6 on 2025-09-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Portfolio Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expected_return', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Expected Return')),
                ('volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Volatility')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Max Drawdown')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Weight')),
                ('shares', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Shares')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Position',
                'verbose_name_plural': 'Portfolio Positions',
                'ordering': ['-weight'],
                'unique_together': {('portfolio', 'symbol')},
            },
        ),
    ]
